### ISSUE TITLE
Improve Accessibility Service Descriptions

### ISSUE THREAD

**Issue by TheAndroidMaster** [TheAndroidMaster/Status#106]
Not sure if this will prevent the app from being taken down, but it's better than nothing. More info about this can be found [here](https://www.reddit.com/r/Android/comments/7c4go5/is_google_play_really_going_to_suspend_all_apps/).

**Comment by kspearrin** [comment]
Our app (password manager) also got this notice: https://github.com/bitwarden/mobile/issues/166

Please let me know if you are able to file a successful appeal, or if simply adjusting your descriptions/disclosures is enough. We're set to lose a pretty critical piece of functionality if we can't use accessibility services. We'll share any info we come across back with you as well.

**Comment by TheAndroidMaster** [comment]
@kspearrin thanks. I'm honestly not sure if there's anything I can do to the accessibility service to make it fit within the guidelines they sent, but I guess I'll find out in 30 days if changing the descriptions is enough (or rather, if it isn't - since they probably won't tell me if it fits within the guidelines, I guess I'll never know unless they choose to suspend it).

**Comment by TheAndroidMaster** [comment]
Google Play supposedly halted the suspension ages ago, and as far as I can tell no more updates have been sent out. I'm going to close this for now, but will reopen if it becomes an issue again.
