### ISSUE TITLE
No 24h time format

### ISSUE THREAD

**Issue by wwp** [TheAndroidMaster/Status#12]
The time always shows as 12h format here whereas system settings is to use a 24h format. Samsung A3 2016 running Android 6.0.1.

**Comment by TheAndroidMaster** [comment]
This was fixed in a commit a couple days ago where a "24 hour time" setting was added under the "clock" section. It will be released in an update later today or tomorrow ;)

**Comment by wwp** [comment]
Great, thanks! And sorry for the noise.. I checked the open/closed issues prior to reporting, didn't check commits.
