### ISSUE TITLE
Cant make new icon set

### ISSUE THREAD

**Issue by PocketKent** [TheAndroidMaster/Status#120]
I was trying to replace the battery icons to be look like Pixel by downloading some material icons. Tried placing the icons on a new set and it dosen't work. What resolution or image I need? Svg?

Running the latest version of Status, 3.7 running on Android 6.0 Marshmallow (Samsung)

**Comment by TheAndroidMaster** [comment]
Any square image file with a transparent background should work, but I'm not sure about svgs. What do you mean by "it doesn't work"? What is it doing? Is there an error message, or do none of the icons appear, or what?

**Comment by TheAndroidMaster** [comment]
As noone else has reported this problem and the issue has been inactive for over a month, I'm closing this issue for now. Feel free to reopen if you feel the need.
