### ISSUE TITLE
Device is incompatible

### ISSUE THREAD

**Issue by Falx** [TheAndroidMaster/Status#124]
I can't install Status on my phone.
How come it is not compatible? Because of android 8? I have a HTC U11+

---

**Affected Device**: HTC U11+

**App Version**: 3.7

**Android Version**: 8.0.0

**Comment by TheAndroidMaster** [comment]
This has already been answered in #87

**Comment by Falx** [comment]
Indeed, sorry just searched on android 8 :-/
