### ISSUE TITLE
Add more icons

### ISSUE THREAD

**Issue by TheAndroidMaster** [TheAndroidMaster/Status#18]
NFC, Priority Mode, Auto Sync, etc...

**Comment by MrNikhilGupta** [comment]
The icon of headphones is needed

**Comment by chrisdlc119** [comment]
Also a new circular battery icon similar to the CyanogenMod's one.

**Comment by TheAndroidMaster** [comment]
@MrNikhilGupta Just added a headphones icon :+1:

**Comment by TheAndroidMaster** [comment]
A VPN icon could also be useful, but [it looks a bit complicated](http://stackoverflow.com/questions/24861034/how-to-find-the-status-of-vpn-connection-through-framework-apis-or-any-other-eff) as the broadcast receiver is deprecated after ICS so it doesn't seem like there are many good ways to listen for status changes.

**Comment by chrisdlc119** [comment]
Oh, that's bad. Maybe only the GPS it's fine.

**Comment by TheAndroidMaster** [comment]
@chrisdlc119 Ah. I forgot about the GPS icon xD

**Comment by TheAndroidMaster** [comment]
I could still add a couple icons, but all the essential icons have been added (with the exclusion of #15) so this isn't really an issue anymore...

**Comment by TheAndroidMaster** [comment]
User suggestions: orientation icon, carrier name, VPN (ugh).

**Comment by TheAndroidMaster** [comment]
Skipping the VPN icon for now. If I find any good examples of how to listen for network changes like this I might implement them, but currently it seems about as easy to add as the dual sim icon :P
