### ISSUE TITLE
James Fenn

### ISSUE THREAD

**Issue by cadialex** [TheAndroidMaster/Status#80]
is the issue. Fix him plz.

@TheAndroidMaster

**Comment by cadialex** [comment]
He won't stop talking French, it's atrocious.

**Comment by TheAndroidMaster** [comment]
Je suis une grosse baguette.

**Comment by TheAndroidMaster** [comment]
J'aime beaucoup le beurre épais.

**Comment by TheAndroidMaster** [comment]
I AM AN OVERSIZED BREAD STICK

**Comment by TheAndroidMaster** [comment]
Je suis une pâtissière muette.
