### ISSUE TITLE
Need option to disable status on lock screen

### ISSUE THREAD

**Issue by natkey** [TheAndroidMaster/Status#83]
This option is needed for some devices like the nexus 5x where the status doesn't fit properly on the lock screen.

**Comment by TheAndroidMaster** [comment]
There isn't any suitable way for Status to detect which screen is referred to as the "lock screen" on every different device, short of documenting the package/activity name of the lock screen for every single phone in existence. An alternative solution could be to find the lock screen activity yourself (probably inside of the SystemUI app) and disable Status manually for that screen.
