### ISSUE TITLE
Battery intensive

### ISSUE THREAD

**Issue by fangovk** [TheAndroidMaster/Status#96]
Huawei Honor 6 battery manager marked Status as high power (intensive) app, from what I see between charging cycles, about 150 mAh .. also, I've noticed Status heats up phone moderately, DU Phone Cooler mark Status as high heat up app, not sure is this normal behaviour or not? .. could you please verify so I can rule out this has to do something with my phone?

thanks!

**Comment by TheAndroidMaster** [comment]
Well I can't verify the accuracy of a battery manager and "phone cooler" (?) I've never heard of before, but Status has a relatively low impact on most devices. If it does affect your phone, there are instructions on how to prevent lag and performance issues in the 'help' (or 'faq', on older versions) section of the app.

**Comment by TheAndroidMaster** [comment]
Marking as invalid and closing. This issue has already been addressed in a previous update.
